### ISSUE TITLE
some questions about the results of soundscapes

### ISSUE THREAD

**Issue by cdxie** [justinsalamon/scaper#62]
hi, I used my own event  to synthesize  soundscapes following the example using the Scaper, in the txtfile, I find that the same event overlapping in time. The result as follows：

4.603466112312178	6.302389493397525	babble
5.111090174762038	7.444187049119387	babble
5.414931605968281	9.862953061306083	music
5.599100623962036	9.988183322552855	music
6.202366268546969	9.510957062119823	music

so, how can I avoid the overlpping for the same event?

**Comment by justinsalamon** [comment]
This is by design: when you specify an event-time distribution, it can occur anywhere in the range spanned by the distribution.

Right now there is no "flag" to tell scaper to avoid overlapping events, so you need to ensure this yourself by specifying event times that don't overlap. You can do this either by explicitly setting the time for each event, or by setting your distribution ranges such that they don't overlap.

An alternative option is to simply sample soundscapes in a loop until you get one that meets your requirements. If you set  `no_audio = True` when you call `generate()` it's extremely fast to generate a soundscape, so you could just generate soundscapes in a loop and check them for overlapping sounds, and when you get a soundscape without overlapping sounds you can save the jams file and then call `generate_from_jams` to obtain the corresponding audio.

In the future I may add an explicit option to control the overlap, but I don't foresee having time to do this in the near future.

**Comment by cdxie** [comment]
Thanks,one point that I don't understand, how to explicitly set the time for each event in the tools？

**Comment by cdxie** [comment]
Another problem is that the sampling rates of the input audio in the foreground or background is 16kz, but the generated audio in the soundscapes is 44.1hz， is that right?

**Comment by cdxie** [comment]
When running the example, I met a mistake as follows:
Generating soundscape: 524/2000
/search/odin/cdxie/ted/speech_data/data_for_SED/Synthetic/scaper-master/scaper/core.py:1172: ScaperWarning: speech event duration (12.00) is greater that source duration (10.02), changing to 10.02
  ScaperWarning)
Generating soundscape: 525/2000
/search/odin/cdxie/ted/speech_data/data_for_SED/Synthetic/scaper-master/scaper/core.py:1172: ScaperWarning: speech event duration (12.00) is greater that source duration (10.02), changing to 10.02
  ScaperWarning)
This install of SoX cannot process .pk files.
Traceback (most recent call last):
  File "/search/speech/cdxie/anaconda3/lib/python3.6/site-packages/sox/core.py", line 118, in soxi
    stderr=subprocess.PIPE
  File "/search/speech/cdxie/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/search/speech/cdxie/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sox', '--i', '-D', 'audio/foreground/music/0bb595c96eb6cb2caa0ebb2702abd3d9_43.pk']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 72, in <module>
    txt_path=txtfile)
  File "/search/odin/cdxie/ted/speech_data/data_for_SED/Synthetic/scaper-master/scaper/core.py", line 1701, in generate
    disable_instantiation_warnings=disable_instantiation_warnings)
  File "/search/odin/cdxie/ted/speech_data/data_for_SED/Synthetic/scaper-master/scaper/core.py", line 1376, in _instantiate
    disable_instantiation_warnings=disable_instantiation_warnings)
  File "/search/odin/cdxie/ted/speech_data/data_for_SED/Synthetic/scaper-master/scaper/core.py", line 1147, in _instantiate_event
    source_duration = sox.file_info.duration(source_file)
  File "/search/speech/cdxie/anaconda3/lib/python3.6/site-packages/sox/file_info.py", line 89, in duration
    output = soxi(input_filepath, 'D')
  File "/search/speech/cdxie/anaconda3/lib/python3.6/site-packages/sox/core.py", line 122, in soxi
    raise SoxiError("SoXI failed with exit code {}".format(cpe.returncode))
sox.core.SoxiError: SoXI failed with exit code 1

How did I solve this problem?

**Comment by justinsalamon** [comment]
Please read the scaper tutorial and documentation, it's explained there.

**Comment by sreenivasaupadhyaya** [comment]
@justinsalamon  Thanks for the information. I was looking for this as well :)
